CREATE DATABASE DBAPI

USE DBAPI

CREATE TABLE CATEGORY(
	ID_CATEGORY INT PRIMARY KEY IDENTITY(1,1),
	DESCRIPTION VARCHAR(50)
)


CREATE TABLE PRODUCT (
	ID_PRODUCT INT PRIMARY KEY IDENTITY(1,1),
	BARCODE VARCHAR(20),
	DESCRIPTION VARCHAR(50),
	BRAND VARCHAR(50),
	ID_CATEGORY INT,
	PRICE DECIMAL(10,2),
	CONSTRAINT FK_IDCATEGORY FOREIGN KEY (ID_CATEGORY) REFERENCES CATEGORY(ID_CATEGORY)
)

INSERT INTO CATEGORY(DESCRIPTION) VALUES
('Tecnologia'),
('ElectroHogar'),
('accesorios')

INSERT INTO PRODUCT(BARCODE, DESCRIPTION, BRAND, ID_CATEGORY, PRICE) VALUES
('50910010', 'Monitor AOC- Curvo Gaming', 'AOC', 1, 1200),
('50910012', 'Lavadora 21 KG WLA - 21', 'WINIA', 2, 1749)



